server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/agms_crop_db

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG